name: NPM Build

on:
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "10"
          cache: "npm"
      - name: NPM Install
        run: npm install
      - name: NPM Lint
        run: npm run lint
